### PR TITLE
Added NewTurn function. Updated market testing

### LINKED ISSUE #63: Market.BuyRoboticonOre() should be private
I think only the market should decide whether it should perform this operation so it should be private not public. We dont want any class to be able to call this

### PR DESCRIPTION
**Pull request by Mart500**
Fixes #63

### CODE REVIEW

**Comment by Mikeywalsh** [comment]
A bit more explanation with each pull request would be nice.
Also, this literally breaks the game, since you havent implemented this into TurnController. Can you try to run the game and playtest it a bit before you try to do a pull request. Also merge with master to catch up now that the finished game is on it.

**Review by Mikeywalsh — CHANGES_REQUESTED** [review]
A bit more explanation with each pull request would be nice.
Also, this literally breaks the game, since you havent implemented this into TurnController. Can you try to run the game and playtest it a bit before you try to do a pull request. Also merge with master to catch up now that the finished game is on it.

**Comment by Mart500** [comment]
@Mikeywalsh Sorry, shoulda added more info. I can't see where the break is, because master that was merged from was broken anyway. Can't seem to find Exactly where it breaks.

**Comment by Mart500** [comment]
I had a look through Abstract player, input controller and Turn controller. Can't see where Roboticons are actually bought within the market. No mention of BuyRoboticonOre or anything similar

**Pull request closed without merging**
